# Generated by Django 4.1.1 on 2022-09-07 23:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("ki", "0002_category_alter_myuser_is_staff_profile_product_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Phone number(+234.....)",
            ),
        ),
    ]
