# Generated by Django 4.1.1 on 2022-09-16 04:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("ki", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, verbose_name="Date of Birth (yyyy-mm-dd)"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Phone number(+234xxxxxxxxx)",
            ),
        ),
    ]
