# Generated by Django 4.1.1 on 2022-09-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ki", "0005_remove_profile_id_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[
                    ("O", "normal_product"),
                    ("1", "add_to_cart"),
                    ("2", "add_to_cart"),
                ],
                default=0,
            ),
        ),
    ]
