# Generated by Django 4.1.1 on 2022-09-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ki", "0006_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[
                    ("1", "normal_product"),
                    ("2", "add_to_cart"),
                    ("3", "wishlist"),
                ],
                default=0,
            ),
        ),
    ]
