# Generated by Django 4.1.1 on 2022-09-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ki", "0009_alter_product_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(2, "normal_product"), (3, "Add_cart")], default=2
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ki.product"
                    ),
                ),
            ],
        ),
    ]
