# Generated by Django 4.1.1 on 2022-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ki", "0010_add_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_cart",
            name="status",
        ),
        migrations.AddField(
            model_name="product",
            name="status_two",
            field=models.IntegerField(
                choices=[(2, "product"), (3, "Add to Cart")], default=2
            ),
        ),
    ]
