# Generated by Django 4.1.1 on 2022-09-25 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ki", "0013_product_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="username",
        ),
        migrations.AddField(
            model_name="product",
            name="username",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
